name: pp_463
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.1+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  auto_route: ^9.2.0
  flutter_svg: ^2.0.10+1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^7.6.7
  shared_preferences: ^2.2.3
  path_provider: ^2.1.2
  equatable: ^2.0.5

  in_app_review: ^2.0.9
  flutter_app_info: ^1.1.2
  connectivity_plus: ^5.0.2
  flutter_markdown: ^0.6.18+3
  is_first_run: ^1.0.0
  intl: ^0.19.0

  percent_indicator: ^4.2.3

  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flagsmith: ^6.0.0
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.8
  webview_flutter_wkwebview: ^3.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^9.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/elements/

flutter_native_splash:
  image: "assets/images/app_icon.png"
  color: '#FFFFFF'

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"